# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from telefeeds._generated import providers_pb2 as providers__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in providers_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProviderGatewayStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/telefeeds.providers.v1.ProviderGateway/Connect',
                request_serializer=providers__pb2.ProviderFrame.SerializeToString,
                response_deserializer=providers__pb2.ProviderFrame.FromString,
                _registered_method=True)


class ProviderGatewayServicer:
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=providers__pb2.ProviderFrame.FromString,
                    response_serializer=providers__pb2.ProviderFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telefeeds.providers.v1.ProviderGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telefeeds.providers.v1.ProviderGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProviderGateway:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/telefeeds.providers.v1.ProviderGateway/Connect',
            providers__pb2.ProviderFrame.SerializeToString,
            providers__pb2.ProviderFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProviderAdminStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_stream(
                '/telefeeds.providers.v1.ProviderAdmin/Call',
                request_serializer=providers__pb2.ProviderCall.SerializeToString,
                response_deserializer=providers__pb2.ProviderEvent.FromString,
                _registered_method=True)


class ProviderAdminServicer:
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_stream_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=providers__pb2.ProviderCall.FromString,
                    response_serializer=providers__pb2.ProviderEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telefeeds.providers.v1.ProviderAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telefeeds.providers.v1.ProviderAdmin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProviderAdmin:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/telefeeds.providers.v1.ProviderAdmin/Call',
            providers__pb2.ProviderCall.SerializeToString,
            providers__pb2.ProviderEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
