# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import telefeeds_gateway_v1_pb2 as telefeeds__gateway__v1__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telefeeds_gateway_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelegramGatewayStub:
    """Public Telegram user-session gateway. Every RPC requires the metadata header
    `authorization: Bearer <integration_access_token>`.
    Authorization failures include `telefeeds-error-code` trailing metadata whose
    value is the matching AuthorizationErrorCode enum value name.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/telefeeds.telegram.v1.TelegramGateway/Subscribe',
                request_serializer=telefeeds__gateway__v1__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=telefeeds__gateway__v1__pb2.UpdateEnvelope.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/telefeeds.telegram.v1.TelegramGateway/Invoke',
                request_serializer=telefeeds__gateway__v1__pb2.InvokeRequest.SerializeToString,
                response_deserializer=telefeeds__gateway__v1__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.GetSessionSnapshots = channel.unary_unary(
                '/telefeeds.telegram.v1.TelegramGateway/GetSessionSnapshots',
                request_serializer=telefeeds__gateway__v1__pb2.GetSessionSnapshotsRequest.SerializeToString,
                response_deserializer=telefeeds__gateway__v1__pb2.GetSessionSnapshotsResponse.FromString,
                _registered_method=True)
        self.BeginPhoneAuthorization = channel.unary_unary(
                '/telefeeds.telegram.v1.TelegramGateway/BeginPhoneAuthorization',
                request_serializer=telefeeds__gateway__v1__pb2.BeginPhoneAuthorizationRequest.SerializeToString,
                response_deserializer=telefeeds__gateway__v1__pb2.BeginPhoneAuthorizationResponse.FromString,
                _registered_method=True)
        self.CompletePhoneAuthorization = channel.unary_unary(
                '/telefeeds.telegram.v1.TelegramGateway/CompletePhoneAuthorization',
                request_serializer=telefeeds__gateway__v1__pb2.CompletePhoneAuthorizationRequest.SerializeToString,
                response_deserializer=telefeeds__gateway__v1__pb2.CompletePhoneAuthorizationResponse.FromString,
                _registered_method=True)
        self.CompletePasswordAuthorization = channel.unary_unary(
                '/telefeeds.telegram.v1.TelegramGateway/CompletePasswordAuthorization',
                request_serializer=telefeeds__gateway__v1__pb2.CompletePasswordAuthorizationRequest.SerializeToString,
                response_deserializer=telefeeds__gateway__v1__pb2.CompletePasswordAuthorizationResponse.FromString,
                _registered_method=True)
        self.BeginExistingSessionAuthorization = channel.unary_unary(
                '/telefeeds.telegram.v1.TelegramGateway/BeginExistingSessionAuthorization',
                request_serializer=telefeeds__gateway__v1__pb2.BeginExistingSessionAuthorizationRequest.SerializeToString,
                response_deserializer=telefeeds__gateway__v1__pb2.BeginExistingSessionAuthorizationResponse.FromString,
                _registered_method=True)
        self.CompleteExistingSessionAuthorization = channel.unary_unary(
                '/telefeeds.telegram.v1.TelegramGateway/CompleteExistingSessionAuthorization',
                request_serializer=telefeeds__gateway__v1__pb2.CompleteExistingSessionAuthorizationRequest.SerializeToString,
                response_deserializer=telefeeds__gateway__v1__pb2.CompleteExistingSessionAuthorizationResponse.FromString,
                _registered_method=True)


class TelegramGatewayServicer:
    """Public Telegram user-session gateway. Every RPC requires the metadata header
    `authorization: Bearer <integration_access_token>`.
    Authorization failures include `telefeeds-error-code` trailing metadata whose
    value is the matching AuthorizationErrorCode enum value name.
    """

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginPhoneAuthorization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompletePhoneAuthorization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompletePasswordAuthorization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginExistingSessionAuthorization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteExistingSessionAuthorization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelegramGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=telefeeds__gateway__v1__pb2.SubscribeRequest.FromString,
                    response_serializer=telefeeds__gateway__v1__pb2.UpdateEnvelope.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=telefeeds__gateway__v1__pb2.InvokeRequest.FromString,
                    response_serializer=telefeeds__gateway__v1__pb2.InvokeResponse.SerializeToString,
            ),
            'GetSessionSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionSnapshots,
                    request_deserializer=telefeeds__gateway__v1__pb2.GetSessionSnapshotsRequest.FromString,
                    response_serializer=telefeeds__gateway__v1__pb2.GetSessionSnapshotsResponse.SerializeToString,
            ),
            'BeginPhoneAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginPhoneAuthorization,
                    request_deserializer=telefeeds__gateway__v1__pb2.BeginPhoneAuthorizationRequest.FromString,
                    response_serializer=telefeeds__gateway__v1__pb2.BeginPhoneAuthorizationResponse.SerializeToString,
            ),
            'CompletePhoneAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.CompletePhoneAuthorization,
                    request_deserializer=telefeeds__gateway__v1__pb2.CompletePhoneAuthorizationRequest.FromString,
                    response_serializer=telefeeds__gateway__v1__pb2.CompletePhoneAuthorizationResponse.SerializeToString,
            ),
            'CompletePasswordAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.CompletePasswordAuthorization,
                    request_deserializer=telefeeds__gateway__v1__pb2.CompletePasswordAuthorizationRequest.FromString,
                    response_serializer=telefeeds__gateway__v1__pb2.CompletePasswordAuthorizationResponse.SerializeToString,
            ),
            'BeginExistingSessionAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginExistingSessionAuthorization,
                    request_deserializer=telefeeds__gateway__v1__pb2.BeginExistingSessionAuthorizationRequest.FromString,
                    response_serializer=telefeeds__gateway__v1__pb2.BeginExistingSessionAuthorizationResponse.SerializeToString,
            ),
            'CompleteExistingSessionAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteExistingSessionAuthorization,
                    request_deserializer=telefeeds__gateway__v1__pb2.CompleteExistingSessionAuthorizationRequest.FromString,
                    response_serializer=telefeeds__gateway__v1__pb2.CompleteExistingSessionAuthorizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telefeeds.telegram.v1.TelegramGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telefeeds.telegram.v1.TelegramGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelegramGateway:
    """Public Telegram user-session gateway. Every RPC requires the metadata header
    `authorization: Bearer <integration_access_token>`.
    Authorization failures include `telefeeds-error-code` trailing metadata whose
    value is the matching AuthorizationErrorCode enum value name.
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/telefeeds.telegram.v1.TelegramGateway/Subscribe',
            telefeeds__gateway__v1__pb2.SubscribeRequest.SerializeToString,
            telefeeds__gateway__v1__pb2.UpdateEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telefeeds.telegram.v1.TelegramGateway/Invoke',
            telefeeds__gateway__v1__pb2.InvokeRequest.SerializeToString,
            telefeeds__gateway__v1__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telefeeds.telegram.v1.TelegramGateway/GetSessionSnapshots',
            telefeeds__gateway__v1__pb2.GetSessionSnapshotsRequest.SerializeToString,
            telefeeds__gateway__v1__pb2.GetSessionSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginPhoneAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telefeeds.telegram.v1.TelegramGateway/BeginPhoneAuthorization',
            telefeeds__gateway__v1__pb2.BeginPhoneAuthorizationRequest.SerializeToString,
            telefeeds__gateway__v1__pb2.BeginPhoneAuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompletePhoneAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telefeeds.telegram.v1.TelegramGateway/CompletePhoneAuthorization',
            telefeeds__gateway__v1__pb2.CompletePhoneAuthorizationRequest.SerializeToString,
            telefeeds__gateway__v1__pb2.CompletePhoneAuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompletePasswordAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telefeeds.telegram.v1.TelegramGateway/CompletePasswordAuthorization',
            telefeeds__gateway__v1__pb2.CompletePasswordAuthorizationRequest.SerializeToString,
            telefeeds__gateway__v1__pb2.CompletePasswordAuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginExistingSessionAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telefeeds.telegram.v1.TelegramGateway/BeginExistingSessionAuthorization',
            telefeeds__gateway__v1__pb2.BeginExistingSessionAuthorizationRequest.SerializeToString,
            telefeeds__gateway__v1__pb2.BeginExistingSessionAuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteExistingSessionAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telefeeds.telegram.v1.TelegramGateway/CompleteExistingSessionAuthorization',
            telefeeds__gateway__v1__pb2.CompleteExistingSessionAuthorizationRequest.SerializeToString,
            telefeeds__gateway__v1__pb2.CompleteExistingSessionAuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
